#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
from PIL import Image
import imagehash
import argparse


def _main():
    filename = _parse_options()
    phash = imagehash.phash(Image.open(filename)).__str__()
    print(phash)
    return


def _parse_options():
    '''Parse input options.
    '''
    parser = argparse.ArgumentParser(
            description='Compute perceptual hash (pHash) of image.'
            )
    parser.add_argument(
            'file',
            metavar='FILE',
            type=str,
            help='file to compute the phash of'
            )
    args = parser.parse_args()
    return args.file


if __name__ == '__main__':
    _main()
