#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015 Nico Schlömer
#
# This file is part of matplotlib2tikz.
#
# matplotlib2tikz is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# matplotlib2tikz is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# matplotlib2tikz.  If not, see <http://www.gnu.org/licenses/>.
#
from PIL import Image
#import imagehash
import phash
import argparse

def _main():
    filename = _parse_options()
    #phash = imagehash.phash(Image.open(filename)).__str__()
    h = phash.phash(Image.open(filename))
    print(h)
    return

def _parse_options():
    '''Parse input options.
    '''
    parser = argparse.ArgumentParser(
            description='Compute perceptual hash (pHash) of image.'
            )
    parser.add_argument(
            'file',
            metavar='FILE',
            type=str,
            help='file to compute the phash of'
            )
    args = parser.parse_args()
    return args.file

if __name__ == '__main__':
    _main()
