#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
import argparse
import matplotlib
from importlib import import_module

import testfunctions


def _main():
    # get command line arguments
    test_name = _parse_options()

    # import the test
    test = import_module('testfunctions.' + test_name)

    fig = test.plot()
    print_tree(fig)
    return


def print_tree(obj, indent=''):
    '''Recursively prints the tree structure of the matplotlib object.
    '''
    if isinstance(obj, matplotlib.text.Text):
        print(indent, type(obj).__name__, '("%s")' % obj.get_text())
    else:
        print(indent, type(obj).__name__)

    for child in obj.get_children():
        print_tree(child, indent + '   ')
    return


def _parse_options():
    '''Parse input options.
    '''
    parser = argparse.ArgumentParser(
            description='Visualize the data structure behind a plot.'
            )
    parser.add_argument(
            'test_name',
            metavar='TEST_NAME',
            type=str,
            help='test plot to show'
            )
    args = parser.parse_args()
    return args.test_name


if __name__ == '__main__':
    # execute the test
    _main()
