version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo apt update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive sudo apt install tzdata
      - run: sudo apt install -y texlive-latex-base texlive-latex-extra context
      - run: pip3 install -U pytest pytest-cov excode setuptools setuptools_scm pip --user
      - checkout
      - run: excode README.md test/zzz_readme_test.py --filter python,test
      - run: python3 setup.py bdist_wheel
      - run: mv ./dist/*.whl ./dist/tikzplotlib-0.CI-py3-none-any.whl
      - run: pip3 install "./dist/tikzplotlib-0.CI-py3-none-any.whl[all]" --user
      - run: pip3 check
      # The actual test
      - run:
          command: pytest --cov tikzplotlib
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
